# Data Preparation for Sudoku AI
import json
import os
import random
from static_solver import generate_board, generate_puzzle

TEST_MODE = False  # Set to True to run a test of the one-hot encoding function
TARGET_RAW_DATASET = "data\sudoku_puzzle_dataset_10_10_1_1781226572.json"  # Path to the dataset generated by static_solver.py
PERFORM_SPLIT = True  # Set to True to split the dataset into training and validation sets
TARGET_SPLIT_RATIO = 0.8  # Ratio for splitting the dataset into training and validation sets

def one_hot_encode(board):
    # This function converts a 9x9 Sudoku board into a one-hot encoded 3D tensor. 
    # The output shape is 9x9x10, where:
    # - First dimension: 9 rows
    # - Second dimension: 9 columns
    # - Third dimension: 10 binary values (index 0 for blank/0, indices 1-9 for digits 1-9)
    # For example, a blank cell is [1,0,0,0,0,0,0,0,0,0]
    # and the digit 5 is [0,0,0,0,0,1,0,0,0,0]
    one_hot_board = []
    for row in board:
        one_hot_row = []
        for cell in row:
            one_hot_cell = [0] * 10  # Initialize a list of 10 zeros
            if cell == 0:  # If the cell is blank
                one_hot_cell[0] = 1  # Set the blank indicator to 1
            else:  # If the cell contains a digit 1-9
                one_hot_cell[cell] = 1  # Set the corresponding digit index to 1
            one_hot_row.append(one_hot_cell)
        one_hot_board.append(one_hot_row)
    return one_hot_board

def split_dataset(dataset, train_ratio=0.8):
    # This function splits the dataset into training and validation sets based on the specified ratio.
    random.seed(42)  # Set a seed for reproducibility
    random.shuffle(dataset)  # Shuffle the dataset to ensure randomness
    split_index = int(len(dataset) * train_ratio)  # Calculate the index for splitting
    train_set = dataset[:split_index]  # First part for training
    remaining_set = dataset[split_index:]  # Remaining part, half for validate and half for test
    val_set = remaining_set[:len(remaining_set) // 2]  # First half of remaining for validation
    test_set = remaining_set[len(remaining_set) // 2:]  # Second half of remaining for testing
    return train_set, val_set, test_set

if __name__ == "__main__":
    if TEST_MODE:
        temp_board = generate_board()  # Generate a complete Sudoku board
        puzzle = generate_puzzle(temp_board, num_blanks=10)  # Create a puzzle with 10 blanks
        solution = temp_board  # The solution is the original complete board
        one_hot_puzzle = one_hot_encode(puzzle)  # One-hot encode the puzzle
        one_hot_solution = one_hot_encode(solution)  # One-hot encode the solution

        # Save the one-hot encoded puzzle and solution to a JSON file
        data = {
            "puzzle": one_hot_puzzle,
            "solution": one_hot_solution
        }
        with open("data/sudoku_data.json", "w") as f:
            json.dump(data, f, indent=2)
        print("One-hot encoded test puzzle and solution saved to sudoku_data.json")
    else:
        # Import the sudoku puzzle dataset generated by static_solver.py
        with open(TARGET_RAW_DATASET, 'r') as f:
            dataset = json.load(f)
        print(f"Loaded dataset from {TARGET_RAW_DATASET} with {len(dataset)} puzzles.")

        # one hot encode the puzzles and solutions and export the new dataset to a json file
        one_hot_dataset = []
        for entry in dataset:
            one_hot_puzzle = one_hot_encode(entry['puzzle'])
            one_hot_solution = one_hot_encode(entry['solution'])
            one_hot_dataset.append({
                "puzzle": one_hot_puzzle,
                "solution": one_hot_solution
            })
        
        # Save the one-hot encoded dataset to a new JSON file in the data/encoded folder
        filename = os.path.basename(TARGET_RAW_DATASET).replace("sudoku_puzzle_dataset", "sudoku_puzzle_dataset_one_hot_encoded")
        output_path = os.path.join("data", "encoded", filename)
        with open(output_path, 'w') as f:
            json.dump(one_hot_dataset, f, indent=2)
        print(f"One-hot encoded dataset saved to {output_path}")

        # Optionally, split the dataset into training and validation sets and save them separately
        if PERFORM_SPLIT:
            train_set, val_set, test_set = split_dataset(one_hot_dataset, train_ratio=TARGET_SPLIT_RATIO)
            train_output_path = os.path.join("data", "encoded", "split", filename.replace(".json", "_train.json"))
            val_output_path = os.path.join("data", "encoded", "split", filename.replace(".json", "_val.json"))
            test_output_path = os.path.join("data", "encoded", "split", filename.replace(".json", "_test.json"))
            with open(train_output_path, 'w') as f:
                json.dump(train_set, f, indent=2)
            with open(val_output_path, 'w') as f:
                json.dump(val_set, f, indent=2)
            with open(test_output_path, 'w') as f:
                json.dump(test_set, f, indent=2)
            print(f"Training set saved to {train_output_path} with {len(train_set)} puzzles.")
            print(f"Validation set saved to {val_output_path} with {len(val_set)} puzzles.")
            print(f"Test set saved to {test_output_path} with {len(test_set)} puzzles.")