# Data Preparation for Sudoku AI
import json
import os
import random
import ijson  # Requires pip install ijson
from static_solver import generate_board, generate_puzzle

TEST_MODE = False  # Set to True to run a test of the one-hot encoding function
TARGET_RAW_DATASET = "data/sudoku_puzzle_dataset_1000000_10-40_1_1781310686.json"  # Path to the dataset generated by static_solver.py
PERFORM_SPLIT = True  # Set to True to split the dataset into training and validation sets
TARGET_SPLIT_RATIO = 0.9  # Ratio for splitting the dataset into training and validation sets

def one_hot_encode(board):
    # This function converts a 9x9 Sudoku board into a one-hot encoded 3D tensor. 
    # The output shape is 9x9x10, where:
    # - First dimension: 9 rows
    # - Second dimension: 9 columns
    # - Third dimension: 10 binary values (index 0 for blank/0, indices 1-9 for digits 1-9)
    # For example, a blank cell is [1,0,0,0,0,0,0,0,0,0]
    # and the digit 5 is [0,0,0,0,0,1,0,0,0,0]
    one_hot_board = []
    for row in board:
        one_hot_row = []
        for cell in row:
            one_hot_cell = [0] * 10  # Initialize a list of 10 zeros
            if cell == 0:  # If the cell is blank
                one_hot_cell[0] = 1  # Set the blank indicator to 1
            else:  # If the cell contains a digit 1-9
                one_hot_cell[cell] = 1  # Set the corresponding digit index to 1
            one_hot_row.append(one_hot_cell)
        one_hot_board.append(one_hot_row)
    return one_hot_board

def split_dataset(dataset, train_ratio=0.8):
    # This function splits the dataset into training and validation sets based on the specified ratio.
    random.seed(42)  # Set a seed for reproducibility
    random.shuffle(dataset)  # Shuffle the dataset to ensure randomness
    split_index = int(len(dataset) * train_ratio)  # Calculate the index for splitting
    train_set = dataset[:split_index]  # First part for training
    remaining_set = dataset[split_index:]  # Remaining part, half for validate and half for test
    val_set = remaining_set[:len(remaining_set) // 2]  # First half of remaining for validation
    test_set = remaining_set[len(remaining_set) // 2:]  # Second half of remaining for testing
    return train_set, val_set, test_set

def main(test_mode=TEST_MODE, target_raw_dataset=TARGET_RAW_DATASET, perform_split=PERFORM_SPLIT, target_split_ratio=TARGET_SPLIT_RATIO):
    if test_mode:
        temp_board = generate_board()  # Generate a complete Sudoku board
        puzzle = generate_puzzle(temp_board, num_blanks=10)  # Create a puzzle with 10 blanks
        solution = temp_board  # The solution is the original complete board
        one_hot_puzzle = one_hot_encode(puzzle)  # One-hot encode the puzzle
        one_hot_solution = one_hot_encode(solution)  # One-hot encode the solution

        # Save the one-hot encoded puzzle and solution to a JSON file
        data = {
            "puzzle": one_hot_puzzle,
            "solution": one_hot_solution
        }
        with open("data/sudoku_data_test.json", "w") as f:
            json.dump(data, f, indent=2)
        print("One-hot encoded test puzzle and solution saved to sudoku_data_test.json")
    else:
        # Step 1: Count entries without loading everything
        with open(target_raw_dataset, 'rb') as f:
            count = 0
            for _ in ijson.items(f, 'item'):
                count += 1
        print(f"Dataset contains {count} puzzles.")

        # Step 2: One-hot encode and write to main file incrementally
        filename = os.path.basename(target_raw_dataset).replace("sudoku_puzzle_dataset", "sudoku_puzzle_dataset_one_hot_encoded")
        encoded_dir = os.path.join("data", "encoded")
        if not os.path.exists(encoded_dir):
            os.makedirs(encoded_dir)
        output_path = os.path.join(encoded_dir, filename)

        print(f"Beginning incremental encoding to {output_path}...")
        with open(target_raw_dataset, 'rb') as f_in:
            with open(output_path, 'w') as f_out:
                f_out.write("[\n")
                first = True
                for i, entry in enumerate(ijson.items(f_in, 'item')):
                    if not first:
                        f_out.write(",\n")
                    one_hot_entry = {
                        "puzzle": one_hot_encode(entry['puzzle']),
                        "solution": one_hot_encode(entry['solution'])
                    }
                    f_out.write(json.dumps(one_hot_entry))
                    first = False
                    if (i + 1) % 50000 == 0:
                        print(f"Encoded {i + 1}/{count}...")
                f_out.write("\n]")
        print(f"One-hot encoded dataset saved to {output_path}")

        # Step 3: Split the dataset incrementally (Streaming approach)
        if perform_split:
            split_dir = os.path.join("data", "encoded", "split")
            if not os.path.exists(split_dir):
                os.makedirs(split_dir)
                
            train_output_path = os.path.join(split_dir, filename.replace(".json", "_train.json"))
            val_output_path = os.path.join(split_dir, filename.replace(".json", "_val.json"))
            test_output_path = os.path.join(split_dir, filename.replace(".json", "_test.json"))

            # Shuffle indices instead of loading full objects
            all_indices = list(range(count))
            random.seed(42)
            random.shuffle(all_indices)

            train_count = int(count * target_split_ratio)
            remaining = count - train_count
            val_count = remaining // 2
            test_count = remaining - val_count

            train_idx = set(all_indices[:train_count])
            val_idx = set(all_indices[train_count:train_count + val_count])
            test_idx = set(all_indices[train_count + val_count:])

            print("Splitting encoded file into train/val/test streamally...")
            with open(output_path, 'rb') as f_encoded:
                with open(train_output_path, 'w') as f_train, \
                     open(val_output_path, 'w') as f_val, \
                     open(test_output_path, 'w') as f_test:
                    
                    for f in [f_train, f_val, f_test]: f.write("[\n")
                    
                    states = {"train": True, "val": True, "test": True}
                    
                    for i, entry in enumerate(ijson.items(f_encoded, 'item')):
                        if i in train_idx:
                            if not states["train"]: f_train.write(",\n")
                            f_train.write(json.dumps(entry))
                            states["train"] = False
                        elif i in val_idx:
                            if not states["val"]: f_val.write(",\n")
                            f_val.write(json.dumps(entry))
                            states["val"] = False
                        elif i in test_idx:
                            if not states["test"]: f_test.write(",\n")
                            f_test.write(json.dumps(entry))
                            states["test"] = False
                            
                        if (i + 1) % 50000 == 0:
                            print(f"Split {i + 1}/{count}...")

                    for f in [f_train, f_val, f_test]: f.write("\n]")

            print(f"Split sets saved to {split_dir}")

if __name__ == "__main__":
    main()