# Sudoku AI Model Trainer
import os
import json
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader
import matplotlib.pyplot as plt


# Concept: The model will be trained to predict the solution given the puzzle, so the input will be the one-hot encoded puzzle and the target output will be the one-hot encoded solution. 
# Success Criteria: The loss will be calculated based on how well the predicted output matches the actual solution.

# Training Architecture:
# Framework: PyTorch (nn.Conv2d)
# Splits: 80/10/10 for train/validation/test
# Loss Function: Categorical Cross-Entropy
# Optimizer: Adam
# Batch Size: 64
# Epochs: 100 (with early stopping based on validation loss)
# Early Stop Patience: 10 epochs without improvement in validation loss

# Network Architecture:
# Model Type: Convolutional Neural Network (CNN)
# Input Layer: Receives the 9 x 9 x 10 one-hot encoded puzzle tensor. The 10 channels represent the presence of digits 0-9 in each cell, where index 0 indicates a blank cell and indices 1-9 indicate the presence of digits 1-9.
# Convolutional Layer 1: Uses 16 filters each of 6 unique shapes (2x2, 3x3, 4x4, 2x6, 1x5, 5x1) to scan for immediate cell relationships, 96 parallel channels.
# Convolutional Layer 2 & 3: Scans the outputs of the previous layers to catch wider, interlocking patterns. Compresses the 96 channels down to 32 channels to cause the model to focus on the most relevant features. 
# Output Layer: A final convolutional layer with 10 filters and a Softmax activation function to output a 9x9x10 tensor of probabilities for digits 0-9. 

# Analytics & Visualization:
# Visualization Engine: TensorBoard
# Log location: logs/
# Metrics: Training Loss, Validation Loss, Accuracy, Precision, Recall, F1 Score
# Graphics: Timeline graphs for loss and accuracy, confusion matrices, and sample predictions vs. actual solutions.

TARGET_TRAINING_DATASET = "data/encoded/split/sudoku_puzzle_dataset_one_hot_encoded_50000_6_1_1781278519_train.json"  # Path to the one-hot encoded dataset generated by data_preparer.py

class SudokuDataset(Dataset):
    # Custom dataset wrapper to load a single puzzle and solution and convert them to PyTorch tensors and return them as a pair ready to be handed off.
    def __init__(self, json_data):
        self.data = json_data

    def __len__(self):
        return len(self.data)

    def __getitem__(self, idx):
        item = self.data[idx]
        
        # Convert raw lists to PyTorch tensors
        puzzle = torch.tensor(item['puzzle'], dtype=torch.float32)
        solution = torch.tensor(item['solution'], dtype=torch.long)
        
        # Rearrange the data from (Height, width, Channels) to (Channels, Height, Width) as required by PyTorch's convolutional layers
        puzzle = puzzle.permute(2, 1, 0)
        
        return puzzle, solution

class BlackBoxBreakerCNN(nn.Module):
    # The CNN architecture as described above using PyTorch's nn.Conv2d for convolutional layers
    def __init__(self):
        super(BlackBoxBreakerCNN, self).__init__()
        
        # --- LAYER 1: MULTI-SCALE GEOMETRIC COVERAGE ---
        # Input: 10 channels (one-hot tokens)
        # Output: 16 filters * 6 shapes = 96 channels
        self.conv2x2 = nn.Conv2d(10, 16, kernel_size=2, padding='same')
        self.conv3x3 = nn.Conv2d(10, 16, kernel_size=3, padding='same')
        self.conv4x4 = nn.Conv2d(10, 16, kernel_size=4, padding='same')
        self.conv2x6 = nn.Conv2d(10, 16, kernel_size=(2, 6), padding='same')
        self.conv1x5 = nn.Conv2d(10, 16, kernel_size=(1, 5), padding='same')
        self.conv5x1 = nn.Conv2d(10, 16, kernel_size=(5, 1), padding='same')

        # Feature Regularizer (Added: 2026-06-12)
        self.dropout = nn.Dropout2d(p=0.1)  # Randomly zero out entire channels with a probability to encourage more robust feature learning and prevent overfitting.
        
        # --- LAYER 2: THE SYNTHESIZER ---
        # Input: 96 channels from Layer 1
        # Output: 32 compressed channels
        self.layer2 = nn.Conv2d(96, 32, kernel_size=3, padding='same')
        
        # --- FINAL LAYER: THE PREDICTOR ---
        # Input: 32 compressed channels
        # Output: 10 channels (Raw scores for digits 0-9)
        self.final_layer = nn.Conv2d(32, 10, kernel_size=1)

    def forward(self, x):
        # 1. Run all 6 custom shape lenses in parallel
        out2x2 = F.relu(self.conv2x2(x))
        out3x3 = F.relu(self.conv3x3(x))
        out4x4 = F.relu(self.conv4x4(x))
        out2x6 = F.relu(self.conv2x6(x))
        out1x5 = F.relu(self.conv1x5(x))
        out5x1 = F.relu(self.conv5x1(x))
        
        # 2. Glue the 96 perspectives together along the channel axis
        x1 = torch.cat([out2x2, out3x3, out4x4, out2x6, out1x5, out5x1], dim=1)
        
        # Apply the dropout to the combined feature maps (Added: 2026-06-12)
        x1_regularized = self.dropout(x1)

        # 3. Compress and synthesize down to 32 channels
        x2 = F.relu(self.layer2(x1_regularized)) # use the regularized features
        
        # 4. Output the raw scores for the entire 9x9x10 grid
        logits = self.final_layer(x2)
        return logits

if __name__ == "__main__":
    # Load the one-hot encoded dataset generated by data_preparer.py
    with open(TARGET_TRAINING_DATASET, 'r') as f:
        training_dataset = json.load(f)
    print(f"Loaded one-hot encoded training dataset with {len(training_dataset)} puzzles.")
    
    with open(TARGET_TRAINING_DATASET.replace("_train.json", "_val.json"), 'r') as f:
        validation_dataset = json.load(f)
    print(f"Loaded one-hot encoded validation dataset with {len(validation_dataset)} puzzles.")

    # Create the Dataset instances
    train_dataset = SudokuDataset(training_dataset)
    val_dataset = SudokuDataset(validation_dataset)

    # Create the DataLoaders to Handle the batching strategy
    train_loader = DataLoader(train_dataset, batch_size=64, shuffle=True)
    val_loader = DataLoader(val_dataset, batch_size=64, shuffle=False) # Fixed yardstick!

    # Instantiating the tools
    model = BlackBoxBreakerCNN()
    criterion = nn.CrossEntropyLoss() # Cross-Entropy Loss for the loss function
    optimizer = torch.optim.Adam(model.parameters(), lr=0.001) # Adam for the optimizer
    print(f"Loading {type(model).__name__} model, {type(criterion).__name__} loss function, and {type(optimizer).__name__} optimizer.")
    
    # Learning Rate Scheduler setup (Added: 2026-06-12)
    scheduler = optim.lr_scheduler.ReduceLROnPlateau(
        optimizer,
        mode='min',  # We want to MINIMIZE the validation loss
        factor=0.1,  # Reduce the learning rate by a factor of 10
        patience=5  # Wait for 5 epochs without oscillation before reducing the learning rate
    )

    # Live Plotting Setup
    plt.ion()  # Enable interactive mode for live plotting
    fig, ax = plt.subplots(figsize=(8, 5))
    train_losses = []
    val_losses = []

    # Training configuration and setup
    CHECKPOINT_PATH = "models/sudoku_model_checkpoint_latest.pth"
    start_epoch = 0
    best_val_loss = float('inf')
    patience = 10
    epochs = 100
    epochs_without_improvement = 0

    if os.path.exists(CHECKPOINT_PATH):
        print(f"Found existing checkpoint at {CHECKPOINT_PATH}. Restoring session...")
        checkpoint = torch.load(CHECKPOINT_PATH)
        
        # Restore components in strict order
        model.load_state_dict(checkpoint['model_state_dict'])
        optimizer.load_state_dict(checkpoint['optimizer_state_dict'])
        scheduler.load_state_dict(checkpoint['scheduler_state_dict'])
        
        start_epoch = checkpoint['epoch']
        best_val_loss = checkpoint['best_val_loss']
        train_losses = checkpoint['train_losses']
        val_losses = checkpoint['val_losses']
        print(f"Training will resume from Epoch {start_epoch}. Best Val Loss so far: {best_val_loss:.4f}")
    else:
        print("No checkpoint found. Starting fresh training run.")

    print(f"Initializing {"continued" if start_epoch > 0 else "new"} training for {epochs} epochs with early stopping patience of {patience} epochs.")
    print("\nStarting training loop...")

    # Training the model by iterating through the DataLoader
    for epoch in range(start_epoch, epochs):
        model.train()  # Set the model to training mode
        running_train_loss = 0.0

        for puzzles, solutions in train_loader:
            # Step 1: Clear out the old gradients so past math doesn't pollute the current step.
            optimizer.zero_grad()

            # Step 2: Pass the input batch forward through the network to get the predictions.
            outputs = model(puzzles)
            
            # Step 3: Calculate the error by comparing predictions to the actual targets.
            solutions_integers = torch.argmax(solutions, dim=-1)  # Convert one-hot encoded solutions to integer labels
            loss = criterion(outputs, solutions_integers)

            # Step 4: Compute the gradients using backpropagation.
            loss.backward()

            # Step 5: Let the optimizer step forward and tweak the weights.
            optimizer.step()

            # Accumulate the training loss for reporting
            running_train_loss += loss.item() * puzzles.size(0)

        # Calculate average training loss for the epoch
        epoch_train_loss = running_train_loss / len(train_loader.dataset)

        # Validation
        model.eval()  # Set the model to evaluation mode
        running_val_loss = 0.0

        with torch.no_grad():  # No need to track gradients during validation
            for val_puzzles, val_solutions in val_loader:
                val_outputs = model(val_puzzles)
                val_solutions_integers = torch.argmax(val_solutions, dim=-1)  # Convert one-hot encoded solutions to integer labels
                val_loss = criterion(val_outputs, val_solutions_integers)
                running_val_loss += val_loss.item() * val_puzzles.size(0)
            
        # Calculate average validation loss for the epoch
        epoch_val_loss = running_val_loss / len(val_loader.dataset)

        # Step the learning rate scheduler
        scheduler.step(epoch_val_loss)

        print(f"Epoch {epoch+1}/{epochs} - Train Loss: {epoch_train_loss:.4f} - Val Loss: {epoch_val_loss:.4f}")

        # Save the model checkpoint for this epoch
        checkpoint = {
            'epoch': epoch + 1,
            'model_state_dict': model.state_dict(),
            'optimizer_state_dict': optimizer.state_dict(),
            'scheduler_state_dict': scheduler.state_dict(),
            'best_val_loss': best_val_loss,
            'train_losses': train_losses,
            'val_losses': val_losses
        }
        torch.save(checkpoint, f"models/sudoku_model_checkpoint_{epoch+1}.pth") # Save an epoch checkpoint for posterity
        torch.save(checkpoint, "models/sudoku_model_checkpoint_latest.pth")  # Overwrite the latest checkpoint for reference

        # Add the values to the reporting data
        train_losses.append(epoch_train_loss)
        val_losses.append(epoch_val_loss)
        
        # Update the live plot
        ax.clear()
        ax.plot(range(1, len(train_losses) + 1), train_losses, label='Train Loss', color='blue', linewidth=2)
        ax.plot(range(1, len(val_losses) + 1), val_losses, label='Val Loss', color='orange', linewidth=2)
        ax.set_title('Sudoku AI Training Progression')
        ax.set_xlabel('Epoch')
        ax.set_ylabel('Loss Value')
        ax.legend()
        ax.grid(True, linestyle='--', alpha=0.6)
        
        # Update the display
        plt.draw()
        plt.pause(0.1)  # Brief pause to let GUI update

        # Early stop check
        if epoch_val_loss < best_val_loss:
            best_val_loss = epoch_val_loss
            epochs_without_improvement = 0
            # Save the best model state
            torch.save(model.state_dict(), "models/best_sudoku_model.pth")
        else:
            epochs_without_improvement += 1
            if epochs_without_improvement >= patience:
                print(f"Early stopping triggered at epoch {epoch+1}. Best Val Loss: {best_val_loss:.4f}")
                break

    # Keep the final plot displayed after training completes
    plt.ioff()  # Disable interactive mode
    plt.show()

    print("Training complete. Best model saved as best_sudoku_model.pth")
