# Sudoku AI Model Trainer
import json
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader


# Concept: The model will be trained to predict the solution given the puzzle, so the input will be the one-hot encoded puzzle and the target output will be the one-hot encoded solution. 
# Success Criteria: The loss will be calculated based on how well the predicted output matches the actual solution.

# Training Architecture:
# Framework: PyTorch (nn.Conv2d)
# Splits: 80/10/10 for train/validation/test
# Loss Function: Categorical Cross-Entropy
# Optimizer: Adam
# Batch Size: 64
# Epochs: 100 (with early stopping based on validation loss)
# Early Stop Patience: 10 epochs without improvement in validation loss

# Network Architecture:
# Model Type: Convolutional Neural Network (CNN)
# Input Layer: Receives the 9 x 9 x 10 one-hot encoded puzzle tensor. The 10 channels represent the presence of digits 0-9 in each cell, where index 0 indicates a blank cell and indices 1-9 indicate the presence of digits 1-9.
# Convolutional Layer 1: Uses 16 filters each of 6 unique shapes (2x2, 3x3, 4x4, 2x6, 1x5, 5x1) to scan for immediate cell relationships, 96 parallel channels.
# Convolutional Layer 2 & 3: Scans the outputs of the previous layers to catch wider, interlocking patterns. Compresses the 96 channels down to 32 channels to cause the model to focus on the most relevant features. 
# Output Layer: A final convolutional layer with 10 filters and a Softmax activation function to output a 9x9x10 tensor of probabilities for digits 0-9. 

TARGET_TRAINING_DATASET = "data\encoded\sudoku_puzzle_dataset_one_hot_encoded_10_10_1_1781226572_train.json"  # Path to the one-hot encoded dataset generated by data_preparer.py

class SudokuDataset(Dataset):
    # Custom dataset wrapper to load a single puzzle and solution and convert them to PyTorch tensors and return them as a pair ready to be handed off.
    def __init__(self, json_data):
        self.data = json_data

    def __len__(self):
        return len(self.data)

    def __getitem__(self, idx):
        item = self.data[idx]
        
        # Convert raw lists to PyTorch tensors
        puzzle = torch.tensor(item['puzzle'], dtype=torch.float32)
        solution = torch.tensor(item['solution'], dtype=torch.long)
        
        # Rearrange the data from (Height, width, Channels) to (Channels, Height, Width) as required by PyTorch's convolutional layers
        puzzle = puzzle.permute(2, 1, 0)
        
        return puzzle, solution

class BlackBoxBreakerCNN(nn.Module):
    # The CNN architecture as described above using PyTorch's nn.Conv2d for convolutional layers
    def __init__(self):
        super(BlackBoxBreakerCNN, self).__init__()
        
        # --- LAYER 1: MULTI-SCALE GEOMETRIC COVERAGE ---
        # Input: 10 channels (one-hot tokens)
        # Output: 16 filters * 6 shapes = 96 channels
        self.conv2x2 = nn.Conv2d(10, 16, kernel_size=2, padding='same')
        self.conv3x3 = nn.Conv2d(10, 16, kernel_size=3, padding='same')
        self.conv4x4 = nn.Conv2d(10, 16, kernel_size=4, padding='same')
        self.conv2x6 = nn.Conv2d(10, 16, kernel_size=(2, 6), padding='same')
        self.conv1x5 = nn.Conv2d(10, 16, kernel_size=(1, 5), padding='same')
        self.conv5x1 = nn.Conv2d(10, 16, kernel_size=(5, 1), padding='same')
        
        # --- LAYER 2: THE SYNTHESIZER ---
        # Input: 96 channels from Layer 1
        # Output: 32 compressed channels
        self.layer2 = nn.Conv2d(96, 32, kernel_size=3, padding='same')
        
        # --- FINAL LAYER: THE PREDICTOR ---
        # Input: 32 compressed channels
        # Output: 10 channels (Raw scores for digits 0-9)
        self.final_layer = nn.Conv2d(32, 10, kernel_size=1)

    def forward(self, x):
        # 1. Run all 6 custom shape lenses in parallel
        out2x2 = F.relu(self.conv2x2(x))
        out3x3 = F.relu(self.conv3x3(x))
        out4x4 = F.relu(self.conv4x4(x))
        out2x6 = F.relu(self.conv2x6(x))
        out1x5 = F.relu(self.conv1x5(x))
        out5x1 = F.relu(self.conv5x1(x))
        
        # 2. Glue the 96 perspectives together along the channel axis
        x1 = torch.cat([out2x2, out3x3, out4x4, out2x6, out1x5, out5x1], dim=1)
        
        # 3. Compress and synthesize down to 32 channels
        x2 = F.relu(self.layer2(x1))
        
        # 4. Output the raw scores for the entire 9x9x10 grid
        logits = self.final_layer(x2)
        return logits

if __name__ == "__main__":
    # Load the one-hot encoded dataset generated by data_preparer.py
    with open(TARGET_TRAINING_DATASET, 'r') as f:
        training_dataset = json.load(f)
    print(f"Loaded one-hot encoded training dataset with {len(training_dataset)} puzzles.")
    
    with open(TARGET_TRAINING_DATASET.replace("_train.json", "_val.json"), 'r') as f:
        validation_dataset = json.load(f)
    print(f"Loaded one-hot encoded validation dataset with {len(validation_dataset)} puzzles.")

    # Training configuration and setup
    best_val_loss = float('inf')
    patience = 10
    epochs = 100
    epochs_without_improvement = 0

    # Create the Dataset instances
    train_dataset = SudokuDataset(training_dataset)
    val_dataset = SudokuDataset(validation_dataset)

    # Create the DataLoaders to Handle the batching strategy
    train_loader = DataLoader(train_dataset, batch_size=64, shuffle=True)
    val_loader = DataLoader(val_dataset, batch_size=64, shuffle=False) # Fixed yardstick!

    # Instantiating the tools
    model = BlackBoxBreakerCNN()
    criterion = nn.CrossEntropyLoss() # Cross-Entropy Loss for the loss function
    optimizer = torch.optim.Adam(model.parameters(), lr=0.001) # Adam for the optimizer

    # TODO: Construct the core training loop to iterate over epochs, calculate loss, perform backpropagation, and implement early stopping based on validation loss.
    # Iterating through the DataLoader
    for epoch in range(epochs):
        model.train()  # Set the model to training mode
        running_train_loss = 0.0

        for puzzles, solutions in train_loader:
            # Step 1: Clear out the old gradients so past math doesn't pollute the current step.
            optimizer.zero_grad()

            # Step 2: Pass the input batch forward through the network to get the predictions.
            outputs = model(puzzles)
            
            # Step 3: Calculate the error by comparing predictions to the actual targets.
            loss = criterion(outputs, solutions)

            # Step 4: Compute the gradients using backpropagation.
            loss.backward()

            # Step 5: Let the optimizer step forward and tweak the weights.
            optimizer.step()

            # Accumulate the training loss for reporting
            running_train_loss += loss.item() * puzzles.size(0)

        # Calculate average training loss for the epoch
        epoch_train_loss = running_train_loss / len(train_loader.dataset)

        # Validation
        model.eval()  # Set the model to evaluation mode
        running_val_loss = 0.0

        with torch.no_grad():  # No need to track gradients during validation
            for val_puzzles, val_solutions in val_loader:
                val_outputs = model(val_puzzles)
                val_loss = criterion(val_outputs, val_solutions)
                running_val_loss += val_loss.item() * val_puzzles.size(0)
            
        # Calculate average validation loss for the epoch
        epoch_val_loss = running_val_loss / len(val_loader.dataset)

        print(f"Epoch {epoch+1}/{epochs} - Train Loss: {epoch_train_loss:.4f} - Val Loss: {epoch_val_loss:.4f}")

        # Early stop check
        if epoch_val_loss < best_val_loss:
            best_val_loss = epoch_val_loss
            epochs_without_improvement = 0
            # Save the best model state
            torch.save(model.state_dict(), "best_sudoku_model.pth")
        else:
            epochs_without_improvement += 1
            if epochs_without_improvement >= patience:
                print(f"Early stopping triggered at epoch {epoch+1}. Best Val Loss: {best_val_loss:.4f}")
                break