# Sudoku AI Model Trainer
import json
import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader


# Concept: The model will be trained to predict the solution given the puzzle, so the input will be the one-hot encoded puzzle and the target output will be the one-hot encoded solution. 
# Success Criteria: The loss will be calculated based on how well the predicted output matches the actual solution.

# Training Architecture:
# Framework: PyTorch (nn.Conv2d for convolutional layers, nn.CrossEntropyLoss for the loss function, and torch.optim.Adam for the optimizer)
# Splits: 80/10/10 for train/validation/test
# Loss Function: Categorical Cross-Entropy
# Optimizer: Adam
# Batch Size: 64
# Epochs: 100 (with early stopping based on validation loss)
# Early Stop Patience: 10 epochs without improvement in validation loss

# Network Architecture:
# Model Type: Convolutional Neural Network (CNN)
# Input Layer: Receives the 9 x 9 x 10 one-hot encoded puzzle tensor. The 10 channels represent the presence of digits 0-9 in each cell, where index 0 indicates a blank cell and indices 1-9 indicate the presence of digits 1-9.
# Convolutional Layer 1: Uses 16 filters each of 6 unique shapes (2x2, 3x3, 4x4, 2x6, 1x5, 5x1) to scan for immediate cell relationships, 96 parallel channels.
# Convolutional Layer 2 & 3: Scans the outputs of the previous layers to catch wider, interlocking patterns. Compresses the 96 channels down to 32 channels to cause the model to focus on the most relevant features. 
# Output Layer: A final convolutional layer with 10 filters and a Softmax activation function to output a 9x9x10 tensor of probabilities for digits 0-9. 

TARGET_TRAINING_DATASET = "data\encoded\sudoku_puzzle_dataset_one_hot_encoded_10_10_1_1781226572_train.json"  # Path to the one-hot encoded dataset generated by data_preparer.py

class SudokuDataset(Dataset):
    # Custom dataset wrapper to load a single puzzle and solution and convert them to PyTorch tensors and return them as a pair ready to be handed off.
    def __init__(self, json_data):
        self.data = json_data

    def __len__(self):
        return len(self.data)

    def __getitem__(self, idx):
        item = self.data[idx]
        
        # Convert raw lists to PyTorch tensors
        puzzle = torch.tensor(item['puzzle'], dtype=torch.float32)
        solution = torch.tensor(item['solution'], dtype=torch.long)
        
        # Rearrange the data from (Height, width, Channels) to (Channels, Height, Width) as required by PyTorch's convolutional layers
        puzzle = puzzle.permute(2, 1, 0)
        
        return puzzle, solution

if __name__ == "__main__":
    # Load the one-hot encoded dataset generated by data_preparer.py
    with open(TARGET_TRAINING_DATASET, 'r') as f:
        training_dataset = json.load(f)
    print(f"Loaded one-hot encoded training dataset with {len(training_dataset)} puzzles.")
    
    with open(TARGET_TRAINING_DATASET.replace("_train.json", "_val.json"), 'r') as f:
        validation_dataset = json.load(f)
    print(f"Loaded one-hot encoded validation dataset with {len(validation_dataset)} puzzles.")

    # Create the Dataset instances
    train_dataset = SudokuDataset(training_dataset)
    val_dataset = SudokuDataset(validation_dataset)

    # Create the DataLoaders to Handle the batching strategy
    train_loader = DataLoader(train_dataset, batch_size=64, shuffle=True)
    val_loader = DataLoader(val_dataset, batch_size=64, shuffle=False) # Fixed yardstick!


    # TODO: Define the CNN architecture as described above using PyTorch's nn.Module
    # TODO: Construct the core training loop to iterate over epochs, calculate loss, perform backpropagation, and implement early stopping based on validation loss.